# input/output information
codeFolder: "benchmarks/RE2" # folder with Verilog sources
outFolder: "testOut/RE2" # target folder for intermediate data
prodCircuitTemplate: "prod.v"
clockInput: 'clk'
initRegister: 'init'
lookAhead: "33" # depend on the upper bound of the opread od Mult

# main module under analysis
module: "pipeline_mul" 
moduleFile: "pipeline_mul.v" 
memoryList: ["Imem"]

# Verilog frontend
yosysPath: "yosys"
yosysBMCPath: "yosys-smtbmc"
inductiveyosysBMCBound: "2"
checkyosysBMCBound: "20"
directlycheckyosysBMCBound: "10"
prefixCheck: "True"
yosysAdditionalModules: ["addmodule.so", "show_regs_mems.so", "stuttering.so"]

# Outpute
outputformat: "brief"

# iVerilog
iverilogPath: "iverilog"
vvpPath: "vvp"

# Analysis backend
avrPath: "/mnt/c/Users/wzl08/Desktop/hwcontracts/avr/avr.py"


srcObservations: 
#  - {id: "ADD", cond: "(op_ctr == 8'h01)", attrs: []} # disclose whenever we are executing an ADD
 - {id: "MUL", cond: " instr_retire[7:0] == 8'h02 ", attrs: [ {value: " instr_retire[31:8] ", width: 24} ] } # disclose MUL operand whenever we are executing a MUL
#  - {id: "MUL", cond: "(op_ctr == 8'h02)", attrs: [ {value: "register", width: 32}, {value: "imm_ctr", width: 24} ] }

# Retire predicates
predicateRetire:
 - {id: "Retire", cond: "1", attrs: [{value: "retire", width: 1}]}

### STATE INVARIANT
stateInvariant: 
 - {id: "legal_instr", cond: "decode", attrs: [{value: " ( ex_op == 8'h1 || ex_op == 8'h2 || ex_op == 8'h3 )", width: 1}]}
 - {id: "decode_stage", cond: "decode", attrs: [{value: " ( ex_op == instr_decode[7:0] && ex_imm == instr_decode[31:8] )", width: 1}]}


### INVARIANT
invariant:
#  - {id: "MUL_decode", cond: " decode && instr_decode[7:0] == 8'h02 ", attrs: [{value: " instr_decode[31:8] ", width: 24}]}
 - {id: "MUL_execute", cond: " execute && instr_execute[7:0] == 8'h02 ", attrs: [{value: " instr_execute[31:8] ", width: 24}]}
 - {id: "MUL_IMM", cond: "mult", attrs: [{value: "mul_imm", width: 24}]}
#  - {id: "MUL_EXECUTE2", cond: "ex_op == 8'h02", attrs: [{value: "rd", width: 32}]}


### TARGET
trgObservations: 
  - {id: "Retire", cond: "1", attrs: [{value: "retire", width: 1}] } 
  #- {id: "retire", cond: "retire", attrs: [] } 

### INITIAL STATE\cpu.
state: 
#- {id: "Imem_state", expr: "Imem", width: 1024}
- {id: "mul_res", expr: "mul_res", width: 32 , val : 0}
- {id: "mult", expr: "mult", width: 1 , val : 0}
- {id: "ex_op", expr: "ex_op", width: 8 , val : 0}
- {id: "ex_imm", expr: "ex_imm", width: 24 , val : 0}
- {id: "mul_rd", expr: "mul_rd", width: 32 , val : 0}
- {id: "mul_imm", expr: "mul_imm", width: 32 , val : 0}
- {id: "wb_res", expr: "wb_res", width: 32 , val : 0}
- {id: "wb_we", expr: "wb_we", width: 1 , val : 0}
- {id: "pc_fetch", expr: "pc_fetch", width: 32 , val : 0}
- {id: "pc_decode", expr: "pc_decode", width: 32 , val : 0}
- {id: "pc_execute", expr: "pc_execute", width: 32 , val : 0}
- {id: "pc_retire", expr: "pc_retire", width: 32 , val : 0}
- {id: "register", expr: "register", width: 32 , val : 0}
- {id: "retire", expr: "retire", width: 1 , val : 0}
- {id: "execute", expr: "execute", width: 1 , val : 0}
- {id: "decode", expr: "decode", width: 1 , val : 0}
- {id: "counter", expr: "counter", width: 32 , val : 0}
- {id: "counter_decode", expr: "counter_decode", width: 32 , val : 0}
- {id: "counter_execute", expr: "counter_execute", width: 32 , val : 0}
- {id: "counter_retire", expr: "counter_retire", width: 32 , val : 0}
- {id: "instr_decode", expr: "instr_decode", width: 32 , val : 0}
- {id: "instr_execute", expr: "instr_execute", width: 32 , val : 0}
- {id: "instr_retire", expr: "instr_retire", width: 32 , val : 0}




inputs:
  - {id: "clk", valueLeft: "clk", valueRight: "clk"}
  - {id: "stuttering_signal", valueLeft: "stuttering_left", valueRight: "stuttering_right"}

expandArrays:
 - {filename: "pipeline_mul.v", array: "Imem", i: "32", j: "32", var: "Imem_flat", flatten: "True", mult: "false"}


auxiliaryVariables: 
- {id: "ex_op", value: "ex_op", width: 8}
- {id: "ex_imm", value: "ex_imm", width: 24}
- {id: "pc_d", value: "pc_d", width: 32}
- {id: "pc_e", value: "pc_e", width: 32}
- {id: "pc_w", value: "pc_w", width: 32}
- {id: "pc_r", value: "pc_r", width: 32}
- {id: "mul_res", value: "mul_res", width: 32}
- {id: "mul_rd", value: "mul_rd", width: 32}
- {id: "wb_res", value: "wb_res", width: 32}
- {id: "wb_we", value: "wb_we", width: 1}
- {id: "Imem", width: 1024, value: "Imem_flat"}
- {id: "mult", value: "mult", width: 1}
- {id: "register", value: "register", width: 32}
- {id: "op", value: "op", width: 8}
- {id: "retire", value: "retire", width: 1}
- {id: "rd", value: "rd", width: 32}




